runtime: python27
api_version: 1
threadsafe: yes

handlers:

#- url: /mail
#  script: feedback.py

- url: (.*)/
  static_files: static\1/index.html
  upload: static/index.html

- url: /
  static_dir: static

